---
- name: Install Neo4j Community Edition
  hosts: localhost
  become: yes
  vars:
    neo4j_install_path: "/home/amit/devops/opt/neo4j"
    neo4j_initial_password: "neo4j123"
    cql_query: "CREATE (movies:Movie {Name:'Noah', ReleaseYear:'2014'});"

  tasks:

    - name: Extract Neo4j tar
      unarchive:
        src: /home/amit/devops/dist/neo4j-community-5.10.0-unix.tar.gz
        dest: /home/amit/devops/opt
        remote_src: yes

    - name: Create symbolic link
      file:
        src: /home/amit/devops/opt/neo4j-community-5.10.0
        dest: /home/amit/devops/opt/neo4j
        state: link

    - name: Create neo4j group
      group:
        name: neo4j
        state: present

    - name: Create neo4j user
      user:
        name: neo4j
        group: neo4j
        shell: /bin/bash

    - name: Change ownership
      file:
        path: /home/amit/devops/opt/neo4j-community-5.10.0
        owner: neo4j
        group: neo4j
        recurse: yes
    
    - name: Start Neo4j service
      shell: "{{ neo4j_install_path }}/bin/neo4j start"
      async: 90
      poll: 0

    - name: Wait for Neo4j to start
      wait_for:
        port: 7474
        timeout: 300    

    - name: Change initial password
      shell:  "{{ neo4j_install_path }}/bin/neo4j-admin dbms set-initial-password {{ neo4j_initial_password }}"

    - name: Run Neo4j query from CQL file
      shell: "{{ neo4j_install_path }}/bin/cypher-shell -u neo4j -p {{ neo4j_initial_password }} -f '{{ cql_query }}'"






